### PR TITLE
cleanup and bugfix

### PR DESCRIPTION
**Pull request by SwissalpS**
This fixes a bug where variable was incorrect.
Also mutes all warnings except for 'unused variable xyz'

### CODE REVIEW

**Comment by S-S-X** [comment]
@SwissalpS I would like to say no :no_entry: for this merge, not because of changes but because of huge merge that started fixing a lot of other issues that are already in upstream. There's no point in collecting both broader code style fixes and new functionality that wont touch into most lines that have style issues.

This makes single merge a lot larger change and therefore harder to follow. I would suggest that this change should be merged directly to upstream.
Problems that this merge would fix are from upstream, I specifically avoided changes like this to keep merge as clean as possible: only new functionality without fixing other issues.

Would it be possible to merge this one directly into upstream as it is going to fix a lot of issues that were in upstream already. It would also make this merge cleaner as it would contain just cleanup / code style updates. If this is merger here those will be mixed up into single merge in upstream repo.

These commits changes a lot more than what was intended in API functionality implementation.
In this PR only few lines are fixing commits made into callback API implementation, mostly just lines where `beerchat.execute_callbacks` are called and results checked.

**Comment by S-S-X** [comment]
Maybe I should still pull commits that are bugfixes for callback API implementation. I'll just cherry-pick those commits from you repo and add those commits here. git will still handle it nicely with separate merge for code style and callback API.

**Comment by SwissalpS** [comment]
@S-S-X  it fixes mainly problems introduced with refactor and allows luacheck to pass with less errors, do as you feel is best :D

**Comment by S-S-X** [comment]
>  it fixes mainly problems introduced with refactor

No it does not, it changes huge amount of lines that were not touched in:
* chatcommands.lua
* whisper.lua
* hash.lua

Btw you can use `git blame` to see actual changes in past commits and who made those changes, for good overview combine with `git log` to pick commits for blame command.

Also you can check diff between this branch and upstream to see what was changed during implementing callback API, take a look at chatcommands.lua and see the difference in changed lines. From this repo master branch that is included callback API PR changes only touch lines where callbacks are used. Compare with commits that code style fixes would add there.

Only ones that were from "refactor" were ones calling callbacks. Check history for that fact.

I've cherry picked commits  that fixes bug (variable names) and style where it only touches things that were changed during implementing callback api functionality.
```
commit 4d85efab33afdd8180250454d8119afba0f5b18b (HEAD -> master, origin/master, origin/HEAD)
Author: SwissalpS <Luke@SwissalpS.ws>
Date:   Mon Feb 17 19:39:14 2020 +0100

    bugfix: wrong variable name

commit b9d1f7aabc941131f97d4ad46061a12712589519
Author: SwissalpS <Luke@SwissalpS.ws>
Date:   Mon Feb 17 19:15:25 2020 +0100

    long lines fix jail.lua

    and a minor fix for beerchat.main_channel_name in message
```

Here also links to compare with upstream in github:
* https://github.com/minetest-beerchat/beerchat/compare/master...SwissalpS:SXrefactor (you have to click load diff because chacommands.lua diff is too large to display)
* https://github.com/minetest-beerchat/beerchat/compare/master...S-S-X:master

**Comment by S-S-X** [comment]
Everything merged to upstream, closing this one and syncing from upstream.

**Pull request closed without merging**
